In [22]:
import pandas as pd

# based on /Volumes/g_psyplafor_methlab$/Students/Jonathan/results/runs_luha/2026_kw20/20260513_0936_69ea_svr_rbf_wave1_cohortA / 20260513_0936_69ea_svr_rbf_test_on_cohortB

outlier_data_cohort_a = pd.DataFrame([
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 15, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 83, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_adverb_ratio', 'n_outliers': 3, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_noun_ratio', 'n_outliers': 5, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_verb_ratio', 'n_outliers': 12, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 1, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 3, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_preposition_ratio', 'n_outliers': 3, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 5, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 39, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_interjection_ratio', 'n_outliers': 14, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_NP -> PRP', 'n_outliers': 71, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_VP -> VBG', 'n_outliers': 32, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 10, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 69, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 48, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_VP_ratio', 'n_outliers': 4, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 35, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_n_words', 'n_outliers': 107, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_avg_word_length', 'n_outliers': 9, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 27, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_brunets_index', 'n_outliers': 13, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_honores_statistic', 'n_outliers': 27, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_mattr', 'n_outliers': 61, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_NDW-50', 'n_outliers': 7, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 22, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 23, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_propositional_density', 'n_outliers': 2, 'n_na': 19, 'n_total': 3453},
{'feature': 'lit_content_density', 'n_outliers': 4, 'n_na': 19, 'n_total': 3453},
{'feature': 'sung_frequency_noun', 'n_outliers': 3, 'n_na': 21, 'n_total': 3453},
{'feature': 'sung_AoA_noun', 'n_outliers': 8, 'n_na': 21, 'n_total': 3453},
{'feature': 'sung_familiarity_noun', 'n_outliers': 5, 'n_na': 21, 'n_total': 3453},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 21, 'n_total': 3453},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 21, 'n_total': 3453},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 25, 'n_na': 17, 'n_total': 3453},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 74, 'n_na': 116, 'n_total': 3453},
{'feature': 'pause_std_pause_duration', 'n_outliers': 111, 'n_na': 17, 'n_total': 3453},
{'feature': 'phon_speech_rate', 'n_outliers': 3, 'n_na': 17, 'n_total': 3453},
{'feature': 'phon_articulation_rate', 'n_outliers': 1, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 17, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 10, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 17, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 12, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 34, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 42, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 90, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 325, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 17, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 5, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 164, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 36, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 90, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 2, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 37, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 13, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 42, 'n_na': 17, 'n_total': 3453},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 55, 'n_na': 17, 'n_total': 3453},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3453},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3453},
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 14, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 91, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_adverb_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_noun_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_verb_ratio', 'n_outliers': 11, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 2, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_preposition_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 5, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 45, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_interjection_ratio', 'n_outliers': 12, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_NP -> PRP', 'n_outliers': 78, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_VP -> VBG', 'n_outliers': 30, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 9, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 43, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 53, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_NP_ratio', 'n_outliers': 0, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_VP_ratio', 'n_outliers': 3, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 35, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_n_words', 'n_outliers': 110, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_avg_word_length', 'n_outliers': 12, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 28, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_brunets_index', 'n_outliers': 11, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_honores_statistic', 'n_outliers': 24, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_mattr', 'n_outliers': 55, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_NDW-50', 'n_outliers': 5, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 21, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 19, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_propositional_density', 'n_outliers': 1, 'n_na': 18, 'n_total': 3465},
{'feature': 'lit_content_density', 'n_outliers': 2, 'n_na': 18, 'n_total': 3465},
{'feature': 'sung_frequency_noun', 'n_outliers': 3, 'n_na': 20, 'n_total': 3465},
{'feature': 'sung_AoA_noun', 'n_outliers': 7, 'n_na': 20, 'n_total': 3465},
{'feature': 'sung_familiarity_noun', 'n_outliers': 5, 'n_na': 20, 'n_total': 3465},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 20, 'n_total': 3465},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 20, 'n_total': 3465},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 26, 'n_na': 14, 'n_total': 3465},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 77, 'n_na': 100, 'n_total': 3465},
{'feature': 'pause_std_pause_duration', 'n_outliers': 110, 'n_na': 14, 'n_total': 3465},
{'feature': 'phon_speech_rate', 'n_outliers': 2, 'n_na': 14, 'n_total': 3465},
{'feature': 'phon_articulation_rate', 'n_outliers': 0, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 16, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 11, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 21, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 13, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 35, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 46, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 87, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 345, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 13, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 6, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 159, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 35, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 84, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 3, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 42, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 11, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 50, 'n_na': 14, 'n_total': 3465},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 61, 'n_na': 14, 'n_total': 3465},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3465},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3465},
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 15, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 81, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_adverb_ratio', 'n_outliers': 3, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_noun_ratio', 'n_outliers': 6, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_verb_ratio', 'n_outliers': 14, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 2, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 3, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_preposition_ratio', 'n_outliers': 5, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 5, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 42, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_interjection_ratio', 'n_outliers': 13, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_NP -> PRP', 'n_outliers': 72, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_VP -> VBG', 'n_outliers': 29, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 7, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 40, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 50, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_VP_ratio', 'n_outliers': 4, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 32, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_n_words', 'n_outliers': 107, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_avg_word_length', 'n_outliers': 12, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 29, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_brunets_index', 'n_outliers': 13, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_honores_statistic', 'n_outliers': 28, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_mattr', 'n_outliers': 59, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_NDW-50', 'n_outliers': 7, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 28, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 18, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_propositional_density', 'n_outliers': 2, 'n_na': 17, 'n_total': 3462},
{'feature': 'lit_content_density', 'n_outliers': 3, 'n_na': 17, 'n_total': 3462},
{'feature': 'sung_frequency_noun', 'n_outliers': 3, 'n_na': 20, 'n_total': 3462},
{'feature': 'sung_AoA_noun', 'n_outliers': 8, 'n_na': 20, 'n_total': 3462},
{'feature': 'sung_familiarity_noun', 'n_outliers': 6, 'n_na': 20, 'n_total': 3462},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 20, 'n_total': 3462},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 20, 'n_total': 3462},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 23, 'n_na': 13, 'n_total': 3462},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 77, 'n_na': 112, 'n_total': 3462},
{'feature': 'pause_std_pause_duration', 'n_outliers': 113, 'n_na': 13, 'n_total': 3462},
{'feature': 'phon_speech_rate', 'n_outliers': 3, 'n_na': 13, 'n_total': 3462},
{'feature': 'phon_articulation_rate', 'n_outliers': 1, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 15, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 12, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 20, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 15, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 39, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 44, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 89, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 371, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 15, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 7, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 158, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 36, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 82, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 3, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 38, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 9, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 49, 'n_na': 13, 'n_total': 3462},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 66, 'n_na': 13, 'n_total': 3462},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3462},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3462},
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 14, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 90, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_adverb_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_noun_ratio', 'n_outliers': 7, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_verb_ratio', 'n_outliers': 12, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 1, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 3, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_preposition_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 6, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 39, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_interjection_ratio', 'n_outliers': 11, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_NP -> PRP', 'n_outliers': 67, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_VP -> VBG', 'n_outliers': 29, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 8, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 39, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 44, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_VP_ratio', 'n_outliers': 3, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 33, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_n_words', 'n_outliers': 99, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_avg_word_length', 'n_outliers': 10, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 25, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_brunets_index', 'n_outliers': 13, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_honores_statistic', 'n_outliers': 25, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_mattr', 'n_outliers': 54, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_NDW-50', 'n_outliers': 5, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 26, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 19, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_propositional_density', 'n_outliers': 2, 'n_na': 18, 'n_total': 3462},
{'feature': 'lit_content_density', 'n_outliers': 4, 'n_na': 18, 'n_total': 3462},
{'feature': 'sung_frequency_noun', 'n_outliers': 4, 'n_na': 21, 'n_total': 3462},
{'feature': 'sung_AoA_noun', 'n_outliers': 5, 'n_na': 21, 'n_total': 3462},
{'feature': 'sung_familiarity_noun', 'n_outliers': 6, 'n_na': 21, 'n_total': 3462},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 21, 'n_total': 3462},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 21, 'n_total': 3462},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 20, 'n_na': 15, 'n_total': 3462},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 69, 'n_na': 116, 'n_total': 3462},
{'feature': 'pause_std_pause_duration', 'n_outliers': 104, 'n_na': 15, 'n_total': 3462},
{'feature': 'phon_speech_rate', 'n_outliers': 3, 'n_na': 15, 'n_total': 3462},
{'feature': 'phon_articulation_rate', 'n_outliers': 1, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 14, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 9, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 0, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 15, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 8, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 27, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 42, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 77, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 0, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 325, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 18, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 6, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 147, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 36, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 78, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 3, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 29, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 0, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 15, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 46, 'n_na': 15, 'n_total': 3462},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 58, 'n_na': 15, 'n_total': 3462},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3462},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3462},
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 13, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 83, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_adverb_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_noun_ratio', 'n_outliers': 6, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_verb_ratio', 'n_outliers': 14, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 2, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_preposition_ratio', 'n_outliers': 5, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 43, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_interjection_ratio', 'n_outliers': 11, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_NP -> PRP', 'n_outliers': 76, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_VP -> VBG', 'n_outliers': 29, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 9, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 69, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 53, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_VP_ratio', 'n_outliers': 4, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 35, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_n_words', 'n_outliers': 101, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_avg_word_length', 'n_outliers': 12, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 27, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_brunets_index', 'n_outliers': 13, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_honores_statistic', 'n_outliers': 27, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_mattr', 'n_outliers': 59, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_NDW-50', 'n_outliers': 7, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 26, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 14, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_propositional_density', 'n_outliers': 2, 'n_na': 18, 'n_total': 3459},
{'feature': 'lit_content_density', 'n_outliers': 3, 'n_na': 18, 'n_total': 3459},
{'feature': 'sung_frequency_noun', 'n_outliers': 4, 'n_na': 21, 'n_total': 3459},
{'feature': 'sung_AoA_noun', 'n_outliers': 7, 'n_na': 21, 'n_total': 3459},
{'feature': 'sung_familiarity_noun', 'n_outliers': 6, 'n_na': 21, 'n_total': 3459},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 21, 'n_total': 3459},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 21, 'n_total': 3459},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 21, 'n_na': 14, 'n_total': 3459},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 74, 'n_na': 113, 'n_total': 3459},
{'feature': 'pause_std_pause_duration', 'n_outliers': 104, 'n_na': 14, 'n_total': 3459},
{'feature': 'phon_speech_rate', 'n_outliers': 3, 'n_na': 14, 'n_total': 3459},
{'feature': 'phon_articulation_rate', 'n_outliers': 1, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 14, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 11, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 19, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 15, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 35, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 43, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 90, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 337, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 16, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 7, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 157, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 27, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 89, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 2, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 34, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 9, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 50, 'n_na': 14, 'n_total': 3459},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 70, 'n_na': 14, 'n_total': 3459},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3459},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3459},
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 10, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 84, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_adverb_ratio', 'n_outliers': 4, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_noun_ratio', 'n_outliers': 6, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_verb_ratio', 'n_outliers': 14, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 2, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 4, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_preposition_ratio', 'n_outliers': 5, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 5, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 42, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_interjection_ratio', 'n_outliers': 14, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_NP -> PRP', 'n_outliers': 76, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_VP -> VBG', 'n_outliers': 31, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 6, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 45, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 55, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_VP_ratio', 'n_outliers': 4, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 36, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_n_words', 'n_outliers': 100, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_avg_word_length', 'n_outliers': 12, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 31, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_brunets_index', 'n_outliers': 14, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_honores_statistic', 'n_outliers': 27, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_mattr', 'n_outliers': 59, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_NDW-50', 'n_outliers': 7, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 26, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 19, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_propositional_density', 'n_outliers': 2, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_content_density', 'n_outliers': 3, 'n_na': 20, 'n_total': 3465},
{'feature': 'sung_frequency_noun', 'n_outliers': 3, 'n_na': 23, 'n_total': 3465},
{'feature': 'sung_AoA_noun', 'n_outliers': 6, 'n_na': 23, 'n_total': 3465},
{'feature': 'sung_familiarity_noun', 'n_outliers': 5, 'n_na': 23, 'n_total': 3465},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 23, 'n_total': 3465},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 23, 'n_total': 3465},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 20, 'n_na': 16, 'n_total': 3465},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 70, 'n_na': 108, 'n_total': 3465},
{'feature': 'pause_std_pause_duration', 'n_outliers': 108, 'n_na': 16, 'n_total': 3465},
{'feature': 'phon_speech_rate', 'n_outliers': 3, 'n_na': 16, 'n_total': 3465},
{'feature': 'phon_articulation_rate', 'n_outliers': 1, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 16, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 11, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 18, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 15, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 37, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 46, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 81, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 333, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 12, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 6, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 150, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 37, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 82, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 3, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 39, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 15, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 51, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 61, 'n_na': 16, 'n_total': 3465},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3465},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3465},
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 14, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 87, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_adverb_ratio', 'n_outliers': 4, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_noun_ratio', 'n_outliers': 6, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_verb_ratio', 'n_outliers': 14, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 2, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 4, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_preposition_ratio', 'n_outliers': 5, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 4, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 41, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_interjection_ratio', 'n_outliers': 13, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_NP -> PRP', 'n_outliers': 78, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_VP -> VBG', 'n_outliers': 32, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 7, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 69, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 53, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_VP_ratio', 'n_outliers': 3, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 32, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_n_words', 'n_outliers': 108, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_avg_word_length', 'n_outliers': 11, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 33, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_brunets_index', 'n_outliers': 14, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_honores_statistic', 'n_outliers': 26, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_mattr', 'n_outliers': 59, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_NDW-50', 'n_outliers': 7, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 23, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 20, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_propositional_density', 'n_outliers': 2, 'n_na': 19, 'n_total': 3459},
{'feature': 'lit_content_density', 'n_outliers': 4, 'n_na': 19, 'n_total': 3459},
{'feature': 'sung_frequency_noun', 'n_outliers': 2, 'n_na': 22, 'n_total': 3459},
{'feature': 'sung_AoA_noun', 'n_outliers': 8, 'n_na': 22, 'n_total': 3459},
{'feature': 'sung_familiarity_noun', 'n_outliers': 6, 'n_na': 22, 'n_total': 3459},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 22, 'n_total': 3459},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 22, 'n_total': 3459},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 24, 'n_na': 15, 'n_total': 3459},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 73, 'n_na': 115, 'n_total': 3459},
{'feature': 'pause_std_pause_duration', 'n_outliers': 108, 'n_na': 15, 'n_total': 3459},
{'feature': 'phon_speech_rate', 'n_outliers': 3, 'n_na': 15, 'n_total': 3459},
{'feature': 'phon_articulation_rate', 'n_outliers': 1, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 15, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 10, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 18, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 14, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 32, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 45, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 88, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 322, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 18, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 6, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 158, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 35, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 88, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 3, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 36, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 8, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 49, 'n_na': 15, 'n_total': 3459},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 63, 'n_na': 15, 'n_total': 3459},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3459},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3459},
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 16, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 83, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_adverb_ratio', 'n_outliers': 3, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_noun_ratio', 'n_outliers': 4, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_verb_ratio', 'n_outliers': 12, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 2, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 3, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_preposition_ratio', 'n_outliers': 4, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 5, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 42, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_interjection_ratio', 'n_outliers': 11, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_NP -> PRP', 'n_outliers': 75, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_VP -> VBG', 'n_outliers': 30, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 9, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 43, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 54, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_VP_ratio', 'n_outliers': 4, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 40, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_n_words', 'n_outliers': 109, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_avg_word_length', 'n_outliers': 7, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 23, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_brunets_index', 'n_outliers': 11, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_honores_statistic', 'n_outliers': 22, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_mattr', 'n_outliers': 50, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_NDW-50', 'n_outliers': 6, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 26, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 19, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_propositional_density', 'n_outliers': 1, 'n_na': 21, 'n_total': 3459},
{'feature': 'lit_content_density', 'n_outliers': 3, 'n_na': 21, 'n_total': 3459},
{'feature': 'sung_frequency_noun', 'n_outliers': 3, 'n_na': 23, 'n_total': 3459},
{'feature': 'sung_AoA_noun', 'n_outliers': 6, 'n_na': 23, 'n_total': 3459},
{'feature': 'sung_familiarity_noun', 'n_outliers': 4, 'n_na': 23, 'n_total': 3459},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 23, 'n_total': 3459},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 23, 'n_total': 3459},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 20, 'n_na': 17, 'n_total': 3459},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 68, 'n_na': 116, 'n_total': 3459},
{'feature': 'pause_std_pause_duration', 'n_outliers': 105, 'n_na': 17, 'n_total': 3459},
{'feature': 'phon_speech_rate', 'n_outliers': 2, 'n_na': 17, 'n_total': 3459},
{'feature': 'phon_articulation_rate', 'n_outliers': 2, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 16, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 9, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 20, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 15, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 38, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 48, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 90, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 344, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 16, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 6, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 157, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 35, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 87, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 2, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 35, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 8, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 50, 'n_na': 17, 'n_total': 3459},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 62, 'n_na': 17, 'n_total': 3459},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3459},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3459},
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 12, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 84, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_adverb_ratio', 'n_outliers': 4, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_noun_ratio', 'n_outliers': 7, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_verb_ratio', 'n_outliers': 11, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 2, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 4, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_preposition_ratio', 'n_outliers': 5, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 3, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 39, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_interjection_ratio', 'n_outliers': 14, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_NP -> PRP', 'n_outliers': 77, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_VP -> VBG', 'n_outliers': 31, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 9, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 46, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 52, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_VP_ratio', 'n_outliers': 4, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 35, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_n_words', 'n_outliers': 110, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_avg_word_length', 'n_outliers': 12, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 25, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_brunets_index', 'n_outliers': 12, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_honores_statistic', 'n_outliers': 23, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_mattr', 'n_outliers': 53, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_NDW-50', 'n_outliers': 6, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 28, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 22, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_propositional_density', 'n_outliers': 2, 'n_na': 20, 'n_total': 3465},
{'feature': 'lit_content_density', 'n_outliers': 3, 'n_na': 20, 'n_total': 3465},
{'feature': 'sung_frequency_noun', 'n_outliers': 4, 'n_na': 23, 'n_total': 3465},
{'feature': 'sung_AoA_noun', 'n_outliers': 8, 'n_na': 23, 'n_total': 3465},
{'feature': 'sung_familiarity_noun', 'n_outliers': 5, 'n_na': 23, 'n_total': 3465},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 23, 'n_total': 3465},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 23, 'n_total': 3465},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 17, 'n_na': 16, 'n_total': 3465},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 72, 'n_na': 117, 'n_total': 3465},
{'feature': 'pause_std_pause_duration', 'n_outliers': 108, 'n_na': 16, 'n_total': 3465},
{'feature': 'phon_speech_rate', 'n_outliers': 3, 'n_na': 16, 'n_total': 3465},
{'feature': 'phon_articulation_rate', 'n_outliers': 1, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 19, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 11, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 21, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 14, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 38, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 39, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 85, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 333, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 18, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 6, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 166, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 35, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 83, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 3, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 40, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 12, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 44, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 62, 'n_na': 16, 'n_total': 3465},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3465},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3465},
{'feature': 'lit_verb_noun_ratio', 'n_outliers': 14, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 82, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_adverb_ratio', 'n_outliers': 3, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_noun_ratio', 'n_outliers': 6, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_verb_ratio', 'n_outliers': 12, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 2, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 4, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_preposition_ratio', 'n_outliers': 5, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 6, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 41, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_interjection_ratio', 'n_outliers': 14, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_NP -> PRP', 'n_outliers': 77, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_VP -> VBG', 'n_outliers': 33, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 8, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 41, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 51, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_VP_ratio', 'n_outliers': 3, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 40, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_n_words', 'n_outliers': 108, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_avg_word_length', 'n_outliers': 14, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 31, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_brunets_index', 'n_outliers': 12, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_honores_statistic', 'n_outliers': 24, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_mattr', 'n_outliers': 53, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_NDW-50', 'n_outliers': 6, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 25, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 23, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_propositional_density', 'n_outliers': 2, 'n_na': 19, 'n_total': 3465},
{'feature': 'lit_content_density', 'n_outliers': 4, 'n_na': 19, 'n_total': 3465},
{'feature': 'sung_frequency_noun', 'n_outliers': 2, 'n_na': 22, 'n_total': 3465},
{'feature': 'sung_AoA_noun', 'n_outliers': 8, 'n_na': 22, 'n_total': 3465},
{'feature': 'sung_familiarity_noun', 'n_outliers': 6, 'n_na': 22, 'n_total': 3465},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 0, 'n_na': 22, 'n_total': 3465},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 22, 'n_total': 3465},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 20, 'n_na': 16, 'n_total': 3465},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 74, 'n_na': 112, 'n_total': 3465},
{'feature': 'pause_std_pause_duration', 'n_outliers': 114, 'n_na': 16, 'n_total': 3465},
{'feature': 'phon_speech_rate', 'n_outliers': 2, 'n_na': 16, 'n_total': 3465},
{'feature': 'phon_articulation_rate', 'n_outliers': 1, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 17, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 11, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 20, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 15, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 34, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 42, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 88, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 321, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 19, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 5, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 152, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 32, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 87, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 3, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 44, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 14, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 47, 'n_na': 16, 'n_total': 3465},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 58, 'n_na': 16, 'n_total': 3465},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3465},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3465},
])

outlier_data_cohort_b = pd.DataFrame([
    {'feature': 'lit_verb_noun_ratio', 'n_outliers': 16, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_subordinate_coordinate_conjunction_ratio', 'n_outliers': 94, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_adverb_ratio', 'n_outliers': 4, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_noun_ratio', 'n_outliers': 6, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_verb_ratio', 'n_outliers': 14, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_pronoun_ratio', 'n_outliers': 2, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_personal_pronoun_ratio', 'n_outliers': 5, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_determiner_ratio', 'n_outliers': 0, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_preposition_ratio', 'n_outliers': 5, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_verb_present_participle_ratio', 'n_outliers': 5, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_verb_modal_ratio', 'n_outliers': 48, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_verb_third_person_singular_ratio', 'n_outliers': 0, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_interjection_ratio', 'n_outliers': 15, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_NP -> PRP', 'n_outliers': 84, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_VP -> VBG', 'n_outliers': 34, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_VP -> VBG_PP', 'n_outliers': 9, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_VP -> VBD_NP', 'n_outliers': 52, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_INTJ -> UH', 'n_outliers': 58, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_NP_ratio', 'n_outliers': 1, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_VP_ratio', 'n_outliers': 4, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_avg_n_words_in_NP', 'n_outliers': 39, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_n_words', 'n_outliers': 119, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_avg_word_length', 'n_outliers': 12, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_words_not_in_dict_ratio', 'n_outliers': 31, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_brunets_index', 'n_outliers': 14, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_honores_statistic', 'n_outliers': 28, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_mattr', 'n_outliers': 64, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_NDW-50', 'n_outliers': 7, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_flesch_kincaid', 'n_outliers': 28, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_avg_distance_between_utterances', 'n_outliers': 20, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_prop_utterance_dist_below_05', 'n_outliers': 0, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_propositional_density', 'n_outliers': 2, 'n_na': 23, 'n_total': 3867},
{'feature': 'lit_content_density', 'n_outliers': 4, 'n_na': 23, 'n_total': 3867},
{'feature': 'sung_frequency_noun', 'n_outliers': 3, 'n_na': 26, 'n_total': 3867},
{'feature': 'sung_AoA_noun', 'n_outliers': 8, 'n_na': 26, 'n_total': 3867},
{'feature': 'sung_familiarity_noun', 'n_outliers': 6, 'n_na': 26, 'n_total': 3867},
{'feature': 'sung_ambiguity_noun', 'n_outliers': 2, 'n_na': 26, 'n_total': 3867},
{'feature': 'sung_concreteness_noun', 'n_outliers': 0, 'n_na': 26, 'n_total': 3867},
{'feature': 'pause_fraction_of_pause', 'n_outliers': 22, 'n_na': 18, 'n_total': 3867},
{'feature': 'pause_mean_pause_duration', 'n_outliers': 79, 'n_na': 127, 'n_total': 3867},
{'feature': 'pause_std_pause_duration', 'n_outliers': 119, 'n_na': 18, 'n_total': 3867},
{'feature': 'phon_speech_rate', 'n_outliers': 4, 'n_na': 18, 'n_total': 3867},
{'feature': 'phon_articulation_rate', 'n_outliers': 2, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope', 'n_outliers': 18, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_loudness_sma3_percentile20.0', 'n_outliers': 12, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_loudness_sma3_percentile50.0', 'n_outliers': 4, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_loudness_sma3_percentile80.0', 'n_outliers': 22, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_loudness_sma3_meanRisingSlope', 'n_outliers': 16, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_spectralFlux_sma3_amean', 'n_outliers': 39, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_spectralFlux_sma3_stddevNorm', 'n_outliers': 53, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_mfcc1_sma3_stddevNorm', 'n_outliers': 97, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_mfcc3_sma3_amean', 'n_outliers': 3, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_mfcc3_sma3_stddevNorm', 'n_outliers': 375, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_F1bandwidth_sma3nz_stddevNorm', 'n_outliers': 19, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_F1amplitudeLogRelF0_sma3nz_amean', 'n_outliers': 7, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_alphaRatioV_sma3nz_stddevNorm', 'n_outliers': 175, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_spectralFluxV_sma3nz_stddevNorm', 'n_outliers': 39, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_mfcc1V_sma3nz_stddevNorm', 'n_outliers': 94, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_alphaRatioUV_sma3nz_amean', 'n_outliers': 3, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_spectralFluxUV_sma3nz_amean', 'n_outliers': 41, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_loudnessPeaksPerSec', 'n_outliers': 1, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_VoicedSegmentsPerSec', 'n_outliers': 14, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_MeanUnvoicedSegmentLength', 'n_outliers': 55, 'n_na': 18, 'n_total': 3867},
{'feature': 'smile_equivalentSoundLevel_dBp', 'n_outliers': 71, 'n_na': 18, 'n_total': 3867},
{'feature': 'task_journaling', 'n_outliers': 0, 'n_na': 0, 'n_total': 3867},
{'feature': 'task_picnicScene', 'n_outliers': 0, 'n_na': 0, 'n_total': 3867},
])

In [23]:
split_counts_cohortA = pd.Series({'0.0': 393,
'4.0': 387,
'6.0': 387,
'7.0': 387,
'2.0': 384,
'3.0': 384,
'1.0': 381,
'8.0': 381,
'9.0': 381,
'5.0': 381,}).reset_index()
split_counts_cohortA.query("index != '0.0'").sum()  # number of samples in training set of CV split 0 --> corresponds to the n_total in the data above

index    4.06.07.02.03.01.08.09.05.0
0                               3453
dtype: object

In [28]:
# cohort B is better, trains on most data, only one split, no duplicate persons etc.

outlier_counts = outlier_data_cohort_b.drop_duplicates(subset="feature", keep='first')
outlier_counts['total_imputed'] = outlier_counts['n_outliers'] + outlier_counts['n_na']
outlier_counts['percentage_imputed'] = (outlier_counts['total_imputed'] / outlier_counts['n_total'] * 100).apply(lambda val: f"{val:.2f}%")
outlier_counts.sort_values(by='total_imputed', ascending=False)

outlier_counts.columns = ['Feature', '# Outliers', '# NAs', '# Total', 'Total Imputed', 'Fraction Imputed']
outlier_counts

,Feature,# Outliers,# NAs,# Total,Total Imputed,Fraction Imputed
0,lit_verb_noun_ratio,16,23,3867,39,1.01%
1,lit_subordinate_coordinate_conjunction_ratio,94,23,3867,117,3.03%
2,lit_adverb_ratio,4,23,3867,27,0.70%
3,lit_noun_ratio,6,23,3867,29,0.75%
4,lit_verb_ratio,14,23,3867,37,0.96%
...,...,...,...,...,...,...
61,smile_VoicedSegmentsPerSec,14,18,3867,32,0.83%
62,smile_MeanUnvoicedSegmentLength,55,18,3867,73,1.89%
63,smile_equivalentSoundLevel_dBp,71,18,3867,89,2.30%
64,task_journaling,0,0,3867,0,0.00%
65,task_picnicScene,0,0,3867,0,0.00%

In [29]:
outlier_counts = outlier_counts[outlier_counts.index != 'Overall']
overall_statistic = pd.DataFrame({'# Outliers': [outlier_counts['# Outliers'].sum()], '# Total': [outlier_counts['# Total'].sum()]})
overall_statistic['Fraction Imputed'] = (overall_statistic['# Outliers'] / overall_statistic['# Total'] * 100).apply(lambda x: f"{x:.2f}%")
overall_statistic.index = ['Overall']

outlier_counts = pd.concat([outlier_counts, overall_statistic])
outlier_counts

,Feature,# Outliers,# NAs,# Total,Total Imputed,Fraction Imputed
0,lit_verb_noun_ratio,16,23.0,3867,39.0,1.01%
1,lit_subordinate_coordinate_conjunction_ratio,94,23.0,3867,117.0,3.03%
2,lit_adverb_ratio,4,23.0,3867,27.0,0.70%
3,lit_noun_ratio,6,23.0,3867,29.0,0.75%
4,lit_verb_ratio,14,23.0,3867,37.0,0.96%
...,...,...,...,...,...,...
62,smile_MeanUnvoicedSegmentLength,55,18.0,3867,73.0,1.89%
63,smile_equivalentSoundLevel_dBp,71,18.0,3867,89.0,2.30%
64,task_journaling,0,0.0,3867,0.0,0.00%
65,task_picnicScene,0,0.0,3867,0.0,0.00%
Overall,NaN,2227,NaN,255222,NaN,0.87%

In [26]:
print(outlier_counts.to_latex())

\begin{tabular}{llrrrrll}
\toprule
 & Feature & # Outliers & # NAs & # Total & Total Imputed & Fraction Imputed & Outlier percentage \\
\midrule
0 & lit_verb_noun_ratio & 16 & 23.000000 & 3867 & 39.000000 & 1.01% & NaN \\
1 & lit_subordinate_coordinate_conjunction_ratio & 94 & 23.000000 & 3867 & 117.000000 & 3.03% & NaN \\
2 & lit_adverb_ratio & 4 & 23.000000 & 3867 & 27.000000 & 0.70% & NaN \\
3 & lit_noun_ratio & 6 & 23.000000 & 3867 & 29.000000 & 0.75% & NaN \\
4 & lit_verb_ratio & 14 & 23.000000 & 3867 & 37.000000 & 0.96% & NaN \\
5 & lit_pronoun_ratio & 2 & 23.000000 & 3867 & 25.000000 & 0.65% & NaN \\
6 & lit_personal_pronoun_ratio & 5 & 23.000000 & 3867 & 28.000000 & 0.72% & NaN \\
7 & lit_determiner_ratio & 0 & 23.000000 & 3867 & 23.000000 & 0.59% & NaN \\
8 & lit_preposition_ratio & 5 & 23.000000 & 3867 & 28.000000 & 0.72% & NaN \\
9 & lit_verb_present_participle_ratio & 5 & 23.000000 & 3867 & 28.000000 & 0.72% & NaN \\
10 & lit_verb_modal_ratio & 48 & 23.000000 & 3867 & 71.000000 & 1.84% & NaN \\
11 & lit_verb_third_person_singular_ratio & 0 & 23.000000 & 3867 & 23.000000 & 0.59% & NaN \\
12 & lit_interjection_ratio & 15 & 23.000000 & 3867 & 38.000000 & 0.98% & NaN \\
13 & lit_NP -> PRP & 84 & 23.000000 & 3867 & 107.000000 & 2.77% & NaN \\
14 & lit_VP -> VBG & 34 & 23.000000 & 3867 & 57.000000 & 1.47% & NaN \\
15 & lit_VP -> VBG_PP & 9 & 23.000000 & 3867 & 32.000000 & 0.83% & NaN \\
16 & lit_VP -> VBD_NP & 52 & 23.000000 & 3867 & 75.000000 & 1.94% & NaN \\
17 & lit_INTJ -> UH & 58 & 23.000000 & 3867 & 81.000000 & 2.09% & NaN \\
18 & lit_NP_ratio & 1 & 23.000000 & 3867 & 24.000000 & 0.62% & NaN \\
19 & lit_VP_ratio & 4 & 23.000000 & 3867 & 27.000000 & 0.70% & NaN \\
20 & lit_avg_n_words_in_NP & 39 & 23.000000 & 3867 & 62.000000 & 1.60% & NaN \\
21 & lit_n_words & 119 & 23.000000 & 3867 & 142.000000 & 3.67% & NaN \\
22 & lit_avg_word_length & 12 & 23.000000 & 3867 & 35.000000 & 0.91% & NaN \\
23 & lit_words_not_in_dict_ratio & 31 & 23.000000 & 3867 & 54.000000 & 1.40% & NaN \\
24 & lit_brunets_index & 14 & 23.000000 & 3867 & 37.000000 & 0.96% & NaN \\
25 & lit_honores_statistic & 28 & 23.000000 & 3867 & 51.000000 & 1.32% & NaN \\
26 & lit_mattr & 64 & 23.000000 & 3867 & 87.000000 & 2.25% & NaN \\
27 & lit_NDW-50 & 7 & 23.000000 & 3867 & 30.000000 & 0.78% & NaN \\
28 & lit_flesch_kincaid & 28 & 23.000000 & 3867 & 51.000000 & 1.32% & NaN \\
29 & lit_avg_distance_between_utterances & 20 & 23.000000 & 3867 & 43.000000 & 1.11% & NaN \\
30 & lit_prop_utterance_dist_below_05 & 0 & 23.000000 & 3867 & 23.000000 & 0.59% & NaN \\
31 & lit_propositional_density & 2 & 23.000000 & 3867 & 25.000000 & 0.65% & NaN \\
32 & lit_content_density & 4 & 23.000000 & 3867 & 27.000000 & 0.70% & NaN \\
33 & sung_frequency_noun & 3 & 26.000000 & 3867 & 29.000000 & 0.75% & NaN \\
34 & sung_AoA_noun & 8 & 26.000000 & 3867 & 34.000000 & 0.88% & NaN \\
35 & sung_familiarity_noun & 6 & 26.000000 & 3867 & 32.000000 & 0.83% & NaN \\
36 & sung_ambiguity_noun & 2 & 26.000000 & 3867 & 28.000000 & 0.72% & NaN \\
37 & sung_concreteness_noun & 0 & 26.000000 & 3867 & 26.000000 & 0.67% & NaN \\
38 & pause_fraction_of_pause & 22 & 18.000000 & 3867 & 40.000000 & 1.03% & NaN \\
39 & pause_mean_pause_duration & 79 & 127.000000 & 3867 & 206.000000 & 5.33% & NaN \\
40 & pause_std_pause_duration & 119 & 18.000000 & 3867 & 137.000000 & 3.54% & NaN \\
41 & phon_speech_rate & 4 & 18.000000 & 3867 & 22.000000 & 0.57% & NaN \\
42 & phon_articulation_rate & 2 & 18.000000 & 3867 & 20.000000 & 0.52% & NaN \\
43 & smile_F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope & 18 & 18.000000 & 3867 & 36.000000 & 0.93% & NaN \\
44 & smile_loudness_sma3_percentile20.0 & 12 & 18.000000 & 3867 & 30.000000 & 0.78% & NaN \\
45 & smile_loudness_sma3_percentile50.0 & 4 & 18.000000 & 3867 & 22.000000 & 0.57% & NaN \\
46 & smile_loudness_sma3_percentile80.0 & 22 & 18.000000 & 3867 & 40.000000 & 1.03% & NaN \\
47 & smile_loudness_sma3_meanRisingSlope & 16 & 18.000000 & 3867 & 34.000000 & 0.88% & NaN \\
48 & smile_spectralFlux_sma3_amean & 39 & 18.000000 & 3867 & 57.000000 & 1.47% & NaN \\
49 & smile_spectralFlux_sma3_stddevNorm & 53 & 18.000000 & 3867 & 71.000000 & 1.84% & NaN \\
50 & smile_mfcc1_sma3_stddevNorm & 97 & 18.000000 & 3867 & 115.000000 & 2.97% & NaN \\
51 & smile_mfcc3_sma3_amean & 3 & 18.000000 & 3867 & 21.000000 & 0.54% & NaN \\
52 & smile_mfcc3_sma3_stddevNorm & 375 & 18.000000 & 3867 & 393.000000 & 10.16% & NaN \\
53 & smile_F1bandwidth_sma3nz_stddevNorm & 19 & 18.000000 & 3867 & 37.000000 & 0.96% & NaN \\
54 & smile_F1amplitudeLogRelF0_sma3nz_amean & 7 & 18.000000 & 3867 & 25.000000 & 0.65% & NaN \\
55 & smile_alphaRatioV_sma3nz_stddevNorm & 175 & 18.000000 & 3867 & 193.000000 & 4.99% & NaN \\
56 & smile_spectralFluxV_sma3nz_stddevNorm & 39 & 18.000000 & 3867 & 57.000000 & 1.47% & NaN \\
57 & smile_mfcc1V_sma3nz_stddevNorm & 94 & 18.000000 & 3867 & 112.000000 & 2.90% & NaN \\
58 & smile_alphaRatioUV_sma3nz_amean & 3 & 18.000000 & 3867 & 21.000000 & 0.54% & NaN \\
59 & smile_spectralFluxUV_sma3nz_amean & 41 & 18.000000 & 3867 & 59.000000 & 1.53% & NaN \\
60 & smile_loudnessPeaksPerSec & 1 & 18.000000 & 3867 & 19.000000 & 0.49% & NaN \\
61 & smile_VoicedSegmentsPerSec & 14 & 18.000000 & 3867 & 32.000000 & 0.83% & NaN \\
62 & smile_MeanUnvoicedSegmentLength & 55 & 18.000000 & 3867 & 73.000000 & 1.89% & NaN \\
63 & smile_equivalentSoundLevel_dBp & 71 & 18.000000 & 3867 & 89.000000 & 2.30% & NaN \\
64 & task_journaling & 0 & 0.000000 & 3867 & 0.000000 & 0.00% & NaN \\
65 & task_picnicScene & 0 & 0.000000 & 3867 & 0.000000 & 0.00% & NaN \\
Overall & NaN & 2227 & NaN & 255222 & NaN & NaN & 0.87% \\
\bottomrule
\end{tabular}

In [32]:
feature_names_latex = ['verb\\_noun\\_ratio',
'subordinate\\_coordinate\\_con-junction\\_ratio',
'adverb\\_ratio',
'noun\\_ratio',
'verb\\_ratio',
'pronoun\\_ratio',
'personal\\_pronoun\\_ratio',
'determiner\\_ratio',
'preposition\\_ratio',
'verb\\_present\\_participle\\_ratio',
'verb\\_modal\\_ratio',
'verb\\_third\\_person\\_singular\\_ratio',
'interjection\\_ratio',
'NP -\\textgreater PRP',
'ROOT -\\textgreater FRAG',
'VP -\\textgreater VBG',
'VP -\\textgreater VBG\\_PP',
'VP -\\textgreater VBD\\_NP',
'INTJ -\\textgreater UH',
'NP\\_ratio',
'VP\\_ratio',
'avg\\_n\\_words\\_in\\_NP',
'n\\_words',
'avg\\_word\\_length',
'words\\_not\\_in\\_dict\\_ratio',
'brunets\\_index',
'honores\\_statistic',
'moving\\_average\\_type\\_token\\_ratio',
'n\\_unique\\_in\\_50',
'flesch\\_kincaid',
'avg\\_distance\\_between\\_utterances',
'prop\\_utterance\\_dist\\_below\\_05',
'propositional\\_density',
'content\\_density',
'frequency\\_noun',
'age\\_of\\_acquisition\\_noun',
'familiarity\\_noun',
'ambiguity\\_noun',
'noun\\_concreteness',
'audio\\_length',
'fraction\\_of\\_pause',
'mean\\_duration',
'std\\_duration',
'speech\\_rate',
'articulation\\_rate',
'F0semitoneFrom27.5Hz\\_sma3nz \\_meanRisingSlope',
'loudness\\_sma3\\_percentile20.0',
'loudness\\_sma3\\_percentile50.0',
'loudness\\_sma3\\_percentile80.0',
'loudness\\_sma3\\_meanRisingSlope',
'spectralFlux\\_sma3 \\_amean',
'spectralFlux\\_sma3 \\_stddevNorm',
'mfcc1\\_sma3\\_stddevNorm',
'mfcc3\\_sma3\\_amean',
'mfcc3\\_sma3\\_stddevNorm',
'F1bandwidth\\_sma3nz\\_stddevNorm',
'F1amplitudeLogRelF0\\_sma3nz\\_amean',
'alphaRatioV\\_sma3nz\\_stddevNorm',
'spectralFluxV\\_sma3nz\\_stddevNorm',
'mfcc1V\\_sma3nz\\_stddevNorm',
'alphaRatioUV\\_sma3nz\\_amean',
'spectralFluxUV\\_sma3nz\\_amean',
'loudnessPeaksPerSec',
'VoicedSegmentsPerSec',
'MeanUnvoicedSegmentLength',
'equivalentSoundLevel\\_dBp',]

In [45]:
feature_name_match = {}

manual_mapping = {
    'lit_VP -> VBG': 'VP -\\textgreater VBG',
    'lit_VP -> VBG_PP': 'VP -\\textgreater VBG\\_PP',
    'lit_VP -> VBD_NP': 'VP -\\textgreater VBD\\_NP',
    'lit_INTJ -> UH': 'INTJ -\\textgreater UH',
    'lit_mattr': 'moving\\_average\\_type\\_token\\_ratio',
    'lit_NDW-50': 'n\\_unique\\_in\\_50',
    'sung_AoA_noun': 'age\\_of\\_acquisition\\_noun',
    'sung_concreteness_noun': 'noun\\_concreteness',
    'lit_subordinate_coordinate_conjunction_ratio': 'subordinate\\_coordinate\\_con-junction\\_ratio',
    'lit_NP -> PRP': 'NP -\\textgreater PRP',
}

def clean_feature(feature):
    try:
        return feature.replace("\\", "").replace("_", "").replace(" ", "").replace("lit","").replace("sung","").replace("pause","").replace("smile","").replace("phon","").lower()
    except:
        print(f"Attention: Cannot clean {feature}")
        return None

for f in outlier_counts.Feature.tolist():
    if pd.isna(f):
        continue
    elif f in manual_mapping:
        feature_name_match[f] = manual_mapping[f]
    elif clean_feature(f) in [clean_feature(name) for name in feature_names_latex]:
        matches = [name for name in feature_names_latex if clean_feature(name) == clean_feature(f)]
        if len(matches) > 1:
            print(f"Attention: Multiple matches for {f}: {matches}")
        feature_name_match[f] = matches[0]
    else:
        print(f"No match for {f}")

No match for task_journaling
No match for task_picnicScene

In [46]:
feature_table = """
\\FloatBarrier
\\begingroup
\\renewcommand{\\arraystretch}{0.8} % smaller line spacing
\\begin{longtable}{p{0.2cm}p{6.5cm}p{10.4cm}}
\\caption{Linguistic and acoustic features extracted for the spontaneous speech audio recordings and corresponding transcripts. Reproduced from \\citet{heitz2026towards}.}
\\label{s_tab:speech_features} \\\\
\\toprule
\\multicolumn{3}{l}{\\textbf{\\textit{Feature group}}}\\\\ & \\textbf{Feature name} & \\textbf{Description} \\\\
\\midrule
\\multicolumn{3}{l}{\\textit{Linguistic}}\\\\
 & verb\\_noun\\_ratio & Ratio of verbs to nouns \\\\
 & subordinate\\_coordinate\\_con-junction\\_ratio & Ratio of subordinate to coordinate conjunctions \\\\
 & adverb\\_ratio & Ratio of adverbs to all words \\\\
 & noun\\_ratio & Ratio of nouns to all words \\\\
 & verb\\_ratio & Ratio of verbs to all words \\\\
 & pronoun\\_ratio & Ratio of pronouns to all words \\\\
 \\endfirsthead
 & personal\\_pronoun\\_ratio & Ratio of personal pronouns to all words \\\\
 & determiner\\_ratio & Ratio of determiners to all words \\\\
 & preposition\\_ratio & Ratio of prepositions to all words \\\\
 & verb\\_present\\_participle\\_ratio & Ratio of verbs (present participle) to all words \\\\
 & verb\\_modal\\_ratio & Ratio of modal verbs to all words \\\\
 & verb\\_third\\_person\\_singular\\_ratio & Ratio of verbs in 3rd person singular to all words \\\\
 & interjection\\_ratio & Ratio of interjections (mostly hesitations, such as uh) to all words \\\\
 & NP -\\textgreater PRP & Count based on constituency parsing \\\\
 & ROOT -\\textgreater FRAG & Count based on constituency parsing \\\\
 & VP -\\textgreater VBG & Count based on constituency parsing \\\\
 & VP -\\textgreater VBG\\_PP & Count based on constituency parsing \\\\
 & VP -\\textgreater VBD\\_NP & Count based on constituency parsing \\\\
 & INTJ -\\textgreater UH & Count based on constituency parsing \\\\
 & NP\\_ratio & Ratio of NP constituents \\\\
 & VP\\_ratio & Ratio of VP constituents \\\\
 & avg\\_n\\_words\\_in\\_NP & Average number of words in a noun phrase \\\\
 & n\\_words & Number of words in the transcript \\\\
 & avg\\_word\\_length & Average word length (number of letters) \\\\
 & words\\_not\\_in\\_dict\\_ratio & Number of words not in an English dictionary \\\\
 & brunets\\_index & Brunét's index \\cite{brunet1978vocabulaire}, a measure of lexical richness. \\\\
 & honores\\_statistic & Honoré Statistic \\cite{honore1979some}, a measure of lexical richness \\\\
 & moving\\_average\\_type\\_token\\_ratio & The moving average type-token ratio \\cite{covington2010cutting} with a window size of 20 words \\\\
 & n\\_unique\\_in\\_50 & Average number of unique words in a 50 word sample  \\cite{wisler2020predicting}\\\\
 & flesch\\_kincaid & Flesch-Kincaid Grade Level Formula \\citet{kincaid1975derivation}, a measure of readability. \\\\
 & avg\\_distance\\_between\\_utterances & The average cosine distance between two sentences, based on \\citet{masrani2017detecting}'s implementation \\\\
 & prop\\_utterance\\_dist\\_below\\_05 & Proportion of sentence pairs with cosine distance \\textless{}= 0.5, based on \\citet{masrani2017detecting}. \\\\
 & propositional\\_density & Propositional density \\cite{parsapoor2023performance}: Ratio of verbs, adjectives, adverbs, prepositions, and conjunctions to all words \\\\
 & content\\_density & Content density \\cite{parsapoor2023performance}: Ratio of nouns, verbs, adjectives, and adverbs to all words \\\\
 & frequency\\_noun & Mean word frequency of nouns \\citet{brysbaert2009moving} \\\\
 & age\\_of\\_acquisition\\_noun & Mean age of acquisition of nouns \\citet{brysbaert2019word} \\\\
 & familiarity\\_noun & Mean word familiarity of nouns \\citet{brysbaert2019word} \\\\
 & ambiguity\\_noun & Mean ambiguity of nouns \\citet{hoffman2013semantic} \\\\
 & noun\\_concreteness & Mean concreteness of words \\citet{brysbaert2014concreteness} \\\\
 \\midrule
\\multicolumn{3}{l}{\\textit{Audio | Hand-crafted}}\\\\
 & audio\\_length & Audio length in seconds \\\\
 & fraction\\_of\\_pause & Fraction of pause segments over audio length \\\\
 & mean\\_duration & Mean pause duration \\\\
 & std\\_duration & Standard deviation of pause durations \\\\
 & speech\\_rate & Number of spoken phonemes divided by the total audio length \\\\
 & articulation\\_rate & Number of spoken phonemes divided by the duration of voice-activated segments \\\\
 \\midrule
\\multicolumn{3}{l}{\\textit{Audio | eGeMAPS} \\cite{eyben2015geneva}} \\\\
 & F0semitoneFrom27.5Hz\\_sma3nz \\_meanRisingSlope & The mean rising slope of pitch (logarithmic F0 on a semitone frequency scale) smoothed over time \\\\
 & loudness\\_sma3\\_percentile20.0 & The 20th percentile loudness (perceived signal intensity) \\\\
 & loudness\\_sma3\\_percentile50.0 & The 50th percentile loudness (perceived signal intensity) \\\\
 & loudness\\_sma3\\_percentile80.0 & The 80th percentile loudness (perceived signal intensity) \\\\
 & loudness\\_sma3\\_meanRisingSlope & The mean rising slope of loudness \\\\
 & spectralFlux\\_sma3 \\_amean & Mean Spectral flux (difference of the spectra of two consecutive frames) \\\\
 & spectralFlux\\_sma3 \\_stddevNorm & Standard deviation of spectral flux \\\\
 & mfcc1\\_sma3\\_stddevNorm & Standard deviation of Mel-Frequency Cepstral Coefficient 1 \\\\
 & mfcc3\\_sma3\\_amean & Mean of Mel-Frequency Cepstral Coefficient 3 \\\\
 & mfcc3\\_sma3\\_stddevNorm & Standard deviation of Mel-Frequency Cepstral Coefficient 3 \\\\
 & F1bandwidth\\_sma3nz\\_stddevNorm & Standard deviation of bandwidth of Formant 1 \\\\
 & F1amplitudeLogRelF0\\_sma3nz\\_amean & Mean of the relative energy of Formant 1 relative to Pitch (F0) frequency \\\\
 & alphaRatioV\\_sma3nz\\_stddevNorm & Standard deviation of the alpha ratio (ratio between energy high and low frequency bands) in voiced regions \\\\
 & spectralFluxV\\_sma3nz\\_stddevNorm & Standard deviation of spectral flux in voiced regions \\\\
 & mfcc1V\\_sma3nz\\_stddevNorm & Standard deviation of MFCC 1 in voiced regions \\\\
 & alphaRatioUV\\_sma3nz\\_amean & Mean of the alpha ratio (ratio between energy high and low frequency bands) in unvoiced regions \\\\
 & spectralFluxUV\\_sma3nz\\_amean & Mean of spectral flux in unvoiced regions \\\\
 & loudnessPeaksPerSec & Number of loudness peaks per second \\\\
 & VoicedSegmentsPerSec & Number voiced segments per second \\\\
 & MeanUnvoicedSegmentLength & The mean length of the unvoiced segments \\\\
 & equivalentSoundLevel\\_dBp & Equivalent sound level (LEq) \\\\
 \\bottomrule
\\end{longtable}
\\endgroup
\\FloatBarrier
"""

In [76]:
newlines = []
for line in feature_table.splitlines():
    if line == "\\multicolumn{3}{l}{\\textbf{\\textit{Feature group}}}\\\\ & \\textbf{Feature name} & \\textbf{Description} \\\\":
        #newlines.append("\\multicolumn{5}{l}{\\textbf{\\textit{Feature group}}}\\\\ & \\textbf{Feature name} & \\textbf{Description} & # Outliers & # NA & Percentage Imputed \\\\")
        newlines.append("\\multicolumn{4}{l}{\\textbf{\\textit{Feature group}}}\\\\ & \\textbf{Feature name} & \\textbf{Description} & % Imputed \\\\")
    elif line == "\\begin{longtable}{p{0.2cm}p{6.5cm}p{10.4cm}} ":
        #newlines.append("\\footnotesize\n\\begin{longtable}{p{0.2cm}p{4.5cm}p{6.4cm}p{1.2cm}p{0.9cm}p{1.5cm}} ")
        newlines.append("\\footnotesize\n\\begin{longtable}{p{0.2cm}p{6.5cm}p{9cm}p{1.3cm}} ")
    elif line == "\\caption{Linguistic and acoustic features extracted for the spontaneous speech audio recordings and corresponding transcripts. Reproduced from \\citet{heitz2026towards}.}":
        newlines.append("\\caption{Linguistic and acoustic features extracted for the spontaneous speech audio recordings and corresponding transcripts, reproduced from \\citet{heitz2026towards}. In addition, the table reports the percentage of imputed feature values based on statistics of the 2024 baseline observations and Cohort A follow-up observations, which represents the trained model applied to Cohort B.}")
    elif line.strip().startswith("&"):
        feature_name = line.split("&")[1].strip()
        if feature_name in feature_name_match.values():
            # add outlier_counts for this feature to line, separated with &
            original_feature_name = [k for k, v in feature_name_match.items() if v == feature_name][0]
            outlier_count_entry = outlier_counts[outlier_counts.Feature == original_feature_name]
            outlier_count = outlier_count_entry['# Outliers'].values[0]
            na_count = int(outlier_count_entry['# NAs'].values[0])
            fraction_imputed = outlier_count_entry['Fraction Imputed'].values[0]
            #line = line.replace("\\\\", f" & {outlier_count} & {na_count} & {fraction_imputed} \\\\")
            line = line.replace("\\\\", f" & {fraction_imputed} \\\\")
            newlines.append(line)
        else:
            print(f"ATTENTION: Feature name '{feature_name}' NOT found in mapping.")
            outlier_count, na_count, fraction_imputed = 0, 0, "0.00%"
            #line = line.replace("\\\\", f" & {outlier_count} & {na_count} & {fraction_imputed} \\\\")
            line = line.replace("\\\\", f" & {fraction_imputed} \\\\")
            newlines.append(line)
    else:
        newlines.append(line)

ATTENTION: Feature name 'ROOT -\textgreater FRAG' NOT found in mapping.
ATTENTION: Feature name 'audio\_length' NOT found in mapping.

In [77]:
print("\n".join(newlines).replace("%","\\%"))

\FloatBarrier
\begingroup
\renewcommand{\arraystretch}{0.8} \% smaller line spacing
\footnotesize
\begin{longtable}{p{0.2cm}p{6.5cm}p{9cm}p{1.3cm}}
\caption{Linguistic and acoustic features extracted for the spontaneous speech audio recordings and corresponding transcripts, reproduced from \citet{heitz2026towards}. In addition, the table reports the percentage of imputed feature values based on statistics of the 2024 baseline observations and Cohort A follow-up observations, which represents the trained model applied to Cohort B.}
\label{s_tab:speech_features} \\
\toprule
\multicolumn{4}{l}{\textbf{\textit{Feature group}}}\\ & \textbf{Feature name} & \textbf{Description} & \% Imputed \\
\midrule
\multicolumn{3}{l}{\textit{Linguistic}}\\
 & verb\_noun\_ratio & Ratio of verbs to nouns  & 1.01\% \\
 & subordinate\_coordinate\_con-junction\_ratio & Ratio of subordinate to coordinate conjunctions  & 3.03\% \\
 & adverb\_ratio & Ratio of adverbs to all words  & 0.70\% \\
 & noun\_ratio & Ratio of nouns to all words  & 0.75\% \\
 & verb\_ratio & Ratio of verbs to all words  & 0.96\% \\
 & pronoun\_ratio & Ratio of pronouns to all words  & 0.65\% \\
 \endfirsthead
 & personal\_pronoun\_ratio & Ratio of personal pronouns to all words  & 0.72\% \\
 & determiner\_ratio & Ratio of determiners to all words  & 0.59\% \\
 & preposition\_ratio & Ratio of prepositions to all words  & 0.72\% \\
 & verb\_present\_participle\_ratio & Ratio of verbs (present participle) to all words  & 0.72\% \\
 & verb\_modal\_ratio & Ratio of modal verbs to all words  & 1.84\% \\
 & verb\_third\_person\_singular\_ratio & Ratio of verbs in 3rd person singular to all words  & 0.59\% \\
 & interjection\_ratio & Ratio of interjections (mostly hesitations, such as uh) to all words  & 0.98\% \\
 & NP -\textgreater PRP & Count based on constituency parsing  & 2.77\% \\
 & ROOT -\textgreater FRAG & Count based on constituency parsing  & 0.00\% \\
 & VP -\textgreater VBG & Count based on constituency parsing  & 1.47\% \\
 & VP -\textgreater VBG\_PP & Count based on constituency parsing  & 0.83\% \\
 & VP -\textgreater VBD\_NP & Count based on constituency parsing  & 1.94\% \\
 & INTJ -\textgreater UH & Count based on constituency parsing  & 2.09\% \\
 & NP\_ratio & Ratio of NP constituents  & 0.62\% \\
 & VP\_ratio & Ratio of VP constituents  & 0.70\% \\
 & avg\_n\_words\_in\_NP & Average number of words in a noun phrase  & 1.60\% \\
 & n\_words & Number of words in the transcript  & 3.67\% \\
 & avg\_word\_length & Average word length (number of letters)  & 0.91\% \\
 & words\_not\_in\_dict\_ratio & Number of words not in an English dictionary  & 1.40\% \\
 & brunets\_index & Brunét's index \cite{brunet1978vocabulaire}, a measure of lexical richness.  & 0.96\% \\
 & honores\_statistic & Honoré Statistic \cite{honore1979some}, a measure of lexical richness  & 1.32\% \\
 & moving\_average\_type\_token\_ratio & The moving average type-token ratio \cite{covington2010cutting} with a window size of 20 words  & 2.25\% \\
 & n\_unique\_in\_50 & Average number of unique words in a 50 word sample  \cite{wisler2020predicting} & 0.78\% \\
 & flesch\_kincaid & Flesch-Kincaid Grade Level Formula \citet{kincaid1975derivation}, a measure of readability.  & 1.32\% \\
 & avg\_distance\_between\_utterances & The average cosine distance between two sentences, based on \citet{masrani2017detecting}'s implementation  & 1.11\% \\
 & prop\_utterance\_dist\_below\_05 & Proportion of sentence pairs with cosine distance \textless{}= 0.5, based on \citet{masrani2017detecting}.  & 0.59\% \\
 & propositional\_density & Propositional density \cite{parsapoor2023performance}: Ratio of verbs, adjectives, adverbs, prepositions, and conjunctions to all words  & 0.65\% \\
 & content\_density & Content density \cite{parsapoor2023performance}: Ratio of nouns, verbs, adjectives, and adverbs to all words  & 0.70\% \\
 & frequency\_noun & Mean word frequency of nouns \citet{brysbaert2009moving}  & 0.75\% \\
 & age\_of\_acquisition\_noun & Mean age of acquisition of nouns \citet{brysbaert2019word}  & 0.88\% \\
 & familiarity\_noun & Mean word familiarity of nouns \citet{brysbaert2019word}  & 0.83\% \\
 & ambiguity\_noun & Mean ambiguity of nouns \citet{hoffman2013semantic}  & 0.72\% \\
 & noun\_concreteness & Mean concreteness of words \citet{brysbaert2014concreteness}  & 0.67\% \\
 \midrule
\multicolumn{3}{l}{\textit{Audio | Hand-crafted}}\\
 & audio\_length & Audio length in seconds  & 0.00\% \\
 & fraction\_of\_pause & Fraction of pause segments over audio length  & 1.03\% \\
 & mean\_duration & Mean pause duration  & 5.33\% \\
 & std\_duration & Standard deviation of pause durations  & 3.54\% \\
 & speech\_rate & Number of spoken phonemes divided by the total audio length  & 0.57\% \\
 & articulation\_rate & Number of spoken phonemes divided by the duration of voice-activated segments  & 0.52\% \\
 \midrule
\multicolumn{3}{l}{\textit{Audio | eGeMAPS} \cite{eyben2015geneva}} \\
 & F0semitoneFrom27.5Hz\_sma3nz \_meanRisingSlope & The mean rising slope of pitch (logarithmic F0 on a semitone frequency scale) smoothed over time  & 0.93\% \\
 & loudness\_sma3\_percentile20.0 & The 20th percentile loudness (perceived signal intensity)  & 0.78\% \\
 & loudness\_sma3\_percentile50.0 & The 50th percentile loudness (perceived signal intensity)  & 0.57\% \\
 & loudness\_sma3\_percentile80.0 & The 80th percentile loudness (perceived signal intensity)  & 1.03\% \\
 & loudness\_sma3\_meanRisingSlope & The mean rising slope of loudness  & 0.88\% \\
 & spectralFlux\_sma3 \_amean & Mean Spectral flux (difference of the spectra of two consecutive frames)  & 1.47\% \\
 & spectralFlux\_sma3 \_stddevNorm & Standard deviation of spectral flux  & 1.84\% \\
 & mfcc1\_sma3\_stddevNorm & Standard deviation of Mel-Frequency Cepstral Coefficient 1  & 2.97\% \\
 & mfcc3\_sma3\_amean & Mean of Mel-Frequency Cepstral Coefficient 3  & 0.54\% \\
 & mfcc3\_sma3\_stddevNorm & Standard deviation of Mel-Frequency Cepstral Coefficient 3  & 10.16\% \\
 & F1bandwidth\_sma3nz\_stddevNorm & Standard deviation of bandwidth of Formant 1  & 0.96\% \\
 & F1amplitudeLogRelF0\_sma3nz\_amean & Mean of the relative energy of Formant 1 relative to Pitch (F0) frequency  & 0.65\% \\
 & alphaRatioV\_sma3nz\_stddevNorm & Standard deviation of the alpha ratio (ratio between energy high and low frequency bands) in voiced regions  & 4.99\% \\
 & spectralFluxV\_sma3nz\_stddevNorm & Standard deviation of spectral flux in voiced regions  & 1.47\% \\
 & mfcc1V\_sma3nz\_stddevNorm & Standard deviation of MFCC 1 in voiced regions  & 2.90\% \\
 & alphaRatioUV\_sma3nz\_amean & Mean of the alpha ratio (ratio between energy high and low frequency bands) in unvoiced regions  & 0.54\% \\
 & spectralFluxUV\_sma3nz\_amean & Mean of spectral flux in unvoiced regions  & 1.53\% \\
 & loudnessPeaksPerSec & Number of loudness peaks per second  & 0.49\% \\
 & VoicedSegmentsPerSec & Number voiced segments per second  & 0.83\% \\
 & MeanUnvoicedSegmentLength & The mean length of the unvoiced segments  & 1.89\% \\
 & equivalentSoundLevel\_dBp & Equivalent sound level (LEq)  & 2.30\% \\
 \bottomrule
\end{longtable}
\endgroup
\FloatBarrier